### ISSUE TITLE
hubot-deploy doesn't handle Slack adapter well

### ISSUE THREAD

**Issue by cyc** [atmos/hubot-deploy#59]
Two minor issues with `hubot-deploy` and the `hubot-slack` adapter.

<img width="579" alt="screen shot 2015-10-24 at 2 23 00 pm" src="https://cloud.githubusercontent.com/assets/1501289/10712850/db84dd1a-7a5a-11e5-9489-eb11bb24fd6a.png">

It doesn't seem to translate the slack user to a username properly (see `U041Z6T9P` above).  Also, it doesn't monospace the table by surrounding with a ```` ``` ```` block.

**Comment by willdurand** [comment]
I had to merge this commit for pretty printing: https://github.com/willdurand/hubot-deploy/commit/d56a11ca14c058f2cd708e4257558bcda1254b74.

For users, I did not get that. Maybe you have to use this script: https://github.com/TailorDev/hubot/blob/master/scripts/github-credentials.coffee

**Comment by atmos** [comment]
I'm going to switch this over to event emissions so people can format the results easier per-adapter.

**Comment by cyc** [comment]
>For users, I did not get that. Maybe you have to use this script: https://github.com/TailorDev/hubot/blob/master/scripts/github-credentials.coffee

Nice! That works.

>I'm going to switch this over to event emissions so people can format the results easier per-adapter.

Yes, that is probably the best way.

**Comment by tw0517tw** [comment]
> https://github.com/atmos/hubot-deploy/blob/master/src/scripts/deploy.coffee#L94

The script is using `user.id` in deployments, but in Slack it's `user.name` being the readable username.

**Comment by shaneog** [comment]
`github-credentials` didn't work for me, and I have this same error.

**Comment by atmos** [comment]
I'm doing a pretty upgrade of everything right now and use slack for my personal projects with friends so this will be working. I should have something that's essentially drop in in the coming days.

**Comment by cyc** [comment]
Thanks @atmos, great to hear it! Looking forward to trying out your changes

**Comment by shaneog** [comment]
Awesome, looking forward to it.

**Comment by maletor** [comment]
We recently switched to Slack and had an issue with `hubot-vault`. We needed to add the script to the external JSON scripts file and bring in the dependency to `package.json`.

**Comment by atmos** [comment]
Sorry for that, I'm still trying to figure out exactly why that is. I'm hoping to migrate my slack stuff in the coming days. I've mainly been focused on a hipchat migration at work.

**Comment by jeyb** [comment]
Hey @atmos there are a couple more things you might want to consider:

#### Issue 1 - Brain & Vault
https://github.com/atmos/hubot-deploy/blob/master/src/scripts/token.coffee#L34 sets the user's GitHub token in the vault (which is great since it's encrypted). However, https://github.com/atmos/hubot-deploy/blob/master/src/scripts/deploy.coffee#L52 is pulling it from the brain instead of the vault. This can be fixed fairly easily:

```diff
diff --git a/src/scripts/deploy.coffee b/src/scripts/deploy.coffee
index adf0794..6719d6f 100644
--- a/src/scripts/deploy.coffee
+++ b/src/scripts/deploy.coffee
@@ -49,8 +53,8 @@ module.exports = (robot) ->
       deployment = new Deployment(name, null, null, environment)
 
       user = robot.brain.userForId msg.envelope.user.id
-      if user? and user.githubDeployToken?
-        deployment.setUserToken(user.githubDeployToken)
+      if user? and (token = robot.vault.forUser(user).get(TokenForBrain))?
+        deployment.setUserToken(token)
 
       deployment.latest (err, deployments) ->
         formatter = new Formatters.LatestFormatter(deployment, deployments)
@@ -85,8 +89,8 @@ module.exports = (robot) ->
       return
 
     user = robot.brain.userForId msg.envelope.user.id
-    if user?.githubDeployToken?
-      deployment.setUserToken(user.githubDeployToken)
+    if user? and (token = robot.vault.forUser(user).get(TokenForBrain))?
+      deployment.setUserToken(token)
 
     deployment.user   = user.id
     deployment.room   = msg.message.user.room
```

#### Issue 2 - Chat User
https://github.com/atmos/heaven/blob/003dd9e2ffa6637aaf2eb074b21791608b6c3e55/lib/heaven/notifier/default.rb#L102 uses the user sent from hutbot-deploy, which is also linked to the GitHub user's profile via https://github.com/atmos/heaven/blob/003dd9e2ffa6637aaf2eb074b21791608b6c3e55/lib/heaven/notifier/default.rb#L180. Therefore, I think we should change it to `user.githubLogin` instead of `user.id` as shown:

```diff
diff --git a/src/scripts/deploy.coffee b/src/scripts/deploy.coffee
index 6719d6f..a893827 100644
--- a/src/scripts/deploy.coffee
+++ b/src/scripts/deploy.coffee
@@ -92,7 +92,7 @@ module.exports = (robot) ->
     if user? and (token = robot.vault.forUser(user).get(TokenForBrain))?
       deployment.setUserToken(token)
 
-    deployment.user   = user.id
+    deployment.user   = user.githubLogin || user.id
     deployment.room   = msg.message.user.room
 
     if robot.adapterName is "flowdock"
```

I've tested both these in our integration with Heaven + Hubot + Hubot Deploy + Slack and it works.

**Comment by atmos** [comment]
This is fixed for [your first issue](https://github.com/atmos/hubot-deploy/blob/5b5a85101f07297e53d9e9100b2ef7339598fed0/src/scripts/deploy.coffee#L94-L97). I'm working on upgrading my personal slack right now.

Are you using heaven for chat notifications for the second issue?

**Comment by atmos** [comment]
This should be fix by #101

**Comment by tw0517tw** [comment]
The `hubot deploys <app> in <environment>` command is still showing unreadable `user.id` instead of `user_name`
